### ISSUE TITLE
The rake tasks are unusable

### ISSUE THREAD

**Issue by simonc** [bmizerany/sinatra-activerecord#1]
Hi,

I just tried to use 'sinatra/activerecord/rake' in my Rakefile.
I'm using Bundler to manage my gems.
I get an error about the fact that activerecord cannot be found.

```
no such file to load -- activerecord
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Library/Ruby/Gems/1.8/gems/sinatra-activerecord-0.1.2/lib/sinatra/activerecord/rake.rb:1
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596:in `new_constants_in'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225:in `load_dependency'
/Library/Ruby/Gems/1.8/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239:in `require'
/Users/happynoff/Linagora/OSSA/sshGate-webservice/Rakefile:2
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
```

**Comment by juliend2** [comment]
i have the same error:

```
macbook-pro-de-julien-desrosiers:yegor_sinatra juliend2$ rake -T --trace

(in /Users/juliend2/Sites/yegor_sinatra)
rake aborted!
no such file to load -- activerecord
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/sinatra-activerecord-0.1.2/lib/sinatra/activerecord/rake.rb:1:in `require'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/sinatra-activerecord-0.1.2/lib/sinatra/activerecord/rake.rb:1
/Users/juliend2/Sites/yegor_sinatra/Rakefile:3:in `require'
/Users/juliend2/Sites/yegor_sinatra/Rakefile:3
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2000:in `run'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/gems/rake-0.8.7/bin/rake:31
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/bin/rake:19:in `load'
/Users/juliend2/.rvm/gems/ruby-1.8.7-p299/bin/rake:19
```

here is my Rakefile:

```
require 'bundler'
Bundler.require
require 'sinatra/activerecord/rake'
```

and here is my Gemfile:

```
source :rubygems
gem 'haml'
gem 'padrino-helpers', '0.9.20'
gem 'activerecord', '3.0.4'
gem 'sinatra-activerecord', '0.1.2'
gem 'sqlite3'
gem 'sinatra', '1.1.3
```

**Comment by chensoren** [comment]
you may need require  'active_record' in your main application.

**Comment by bmizerany** [comment]
This is probably because the gemspec doesn't lock you down to a version of AR by not needed AR.  You will need to require AR yourself.

**Comment by simonc** [comment]
Hmm, ok, since it's almost a year old, I don't remember the context in which I was but I just tested and it seems to work. Thanks
